mod 'puppet-nginx'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-concat'
mod 'puppetlabs-apt'
mod 'puppetlabs-translate'
mod 'puppetlabs-powershell'
mod 'puppetlabs-reboot'
mod 'stahnma-epel'
mod 'pltraining-dockeragent'
mod 'puppetlabs-docker', '2.0.0'
